services:
  - type: web
    name: mern-api
    env: node
    region: oregon
    buildCommand: cd server && npm ci && npm run build
    startCommand: cd server && node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true